### ISSUE TITLE
[Feature Request] Windows support receive only mode.

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [MrBeanCpp/Clipboard-Cloud-Client#2]
Poor Chinese, translated by GPT4.0.

非常感谢大佬开发出这款软件，真的是太厉害了！我在使用过程中发现，大多数时间我只是想要实现单向同步（偶尔从iOS同步到Windows），这样对我来说会更方便一些。不知道能否在软件中加入一个配置选项，让用户可以根据需要选择同步的方向呢？能有这样的功能真的会让我受益匪浅！再次向您表达我最深的感激和仰慕🧍‍♂️。

**Comment by MrBeanCpp** [comment]
Okay. I'll support it later.

**Comment by MrBeanCpp** [comment]
See Release `v0.2.0`
